package ffmpegtools

import "testing"

// Alle Fixtures unten sind wörtliche Ausschnitte einer echten
// `ffmpeg 5.1.9`-Ausgabe (nicht erfunden/geraten) — inkl. der beiden
// Live-gefundenen Stolpersteine: (1) ein Enum-Name, der die sonst
// übliche Spaltenauffüllung überschreitet (`autovariance-biased`), und
// (2) eine Option ganz ohne "(default …)".

func TestParseCodecs(t *testing.T) {
	out := `Encoders:
 V..... = Video
 A..... = Audio
 S..... = Subtitle
 .F.... = Frame-level multithreading
 ..S... = Slice-level multithreading
 ...X.. = Codec is experimental
 ....B. = Supports draw_horiz_band
 .....D = Supports direct rendering method 1
 ------
 V....D a64multi             Multicolor charset for Commodore 64 (codec a64_multi)
 V..... libsvtav1            SVT-AV1(Scalable Video Technology for AV1) encoder (codec av1)
 A..... aac                  AAC (Advanced Audio Coding)
 S..... ssa                  ASS (Advanced SubStation Alpha) subtitle (codec ass)
`
	got := ParseCodecs(out)
	if len(got) != 4 {
		t.Fatalf("expected 4 codecs, got %d: %+v", len(got), got)
	}
	if got[0].Name != "a64multi" || got[0].MediaType != "video" || got[0].Flags != "V....D" {
		t.Errorf("unexpected first entry: %+v", got[0])
	}
	if got[0].Description != "Multicolor charset for Commodore 64 (codec a64_multi)" {
		t.Errorf("unexpected description: %q", got[0].Description)
	}
	if got[2].MediaType != "audio" || got[2].Name != "aac" {
		t.Errorf("unexpected audio entry: %+v", got[2])
	}
	if got[3].MediaType != "subtitle" {
		t.Errorf("unexpected subtitle entry: %+v", got[3])
	}
}

func TestParseFormats(t *testing.T) {
	out := `File formats:
 D. = Demuxing supported
 .E = Muxing supported
 --
 D  3dostr          3DO STR
  E 3g2             3GP2 (3GPP2 file format)
 DE ac3             raw AC-3
`
	got := ParseFormats(out)
	if len(got) != 3 {
		t.Fatalf("expected 3 formats, got %d: %+v", len(got), got)
	}
	if got[0].Name != "3dostr" || !got[0].Demuxing || got[0].Muxing {
		t.Errorf("unexpected demux-only entry: %+v", got[0])
	}
	if got[1].Name != "3g2" || got[1].Demuxing || !got[1].Muxing {
		t.Errorf("unexpected mux-only entry: %+v", got[1])
	}
	if got[2].Name != "ac3" || !got[2].Demuxing || !got[2].Muxing {
		t.Errorf("unexpected demux+mux entry: %+v", got[2])
	}
}

func TestParsePixFmts(t *testing.T) {
	out := `Pixel formats:
I.... = Supported Input  format for conversion
.O... = Supported Output format for conversion
..H.. = Hardware accelerated format
...P. = Paletted format
....B = Bitstream format
FLAGS NAME            NB_COMPONENTS BITS_PER_PIXEL BIT_DEPTHS
-----
IO... yuv420p                3             12      8-8-8
IO..B monow                  1              1      1
.O..B bgr4                   3              4      1-2-1
`
	got := ParsePixFmts(out)
	if len(got) != 3 {
		t.Fatalf("expected 3 pix_fmts, got %d: %+v", len(got), got)
	}
	if got[0].Name != "yuv420p" || !got[0].Input || !got[0].Output || got[0].NumComponents != 3 || got[0].BitsPerPixel != 12 || got[0].BitDepths != "8-8-8" {
		t.Errorf("unexpected yuv420p entry: %+v", got[0])
	}
	if !got[1].Bitstream || !got[1].Output {
		t.Errorf("unexpected monow entry: %+v", got[1])
	}
	if got[2].Input {
		t.Errorf("bgr4 should not be flagged as input: %+v", got[2])
	}
}

func TestParseFilters(t *testing.T) {
	out := `Filters:
  T.. = Timeline support
  .S. = Slice threading
  ..C = Command support
  A = Audio input/output
  V = Video input/output
  N = Dynamic number and/or type of input/output
  | = Source or sink filter
 ... acopy             A->A       Copy the input audio unchanged to the output.
 .SC afir              N->N       Apply Finite Impulse Response filter with supplied coefficients in additional stream(s).
 ... aevalsrc          |->A       Generate an audio signal generated by an expression.
 ..C scale             V->V       Scale the input video size and/or convert the image format.
`
	got := ParseFilters(out)
	if len(got) != 4 {
		t.Fatalf("expected 4 filters, got %d: %+v", len(got), got)
	}
	if got[0].Name != "acopy" || got[0].IO != "A->A" {
		t.Errorf("unexpected acopy entry: %+v", got[0])
	}
	if !got[1].SliceThreading || !got[1].CommandSupport || got[1].IO != "N->N" {
		t.Errorf("unexpected afir entry: %+v", got[1])
	}
	if got[2].IO != "|->A" {
		t.Errorf("unexpected aevalsrc IO (source filter): %+v", got[2])
	}
	if !got[3].CommandSupport || got[3].Name != "scale" {
		t.Errorf("unexpected scale entry: %+v", got[3])
	}
}

func TestParseDetailEncoder(t *testing.T) {
	// Ausschnitt aus echtem `ffmpeg -h encoder=libx264` — inkl. des
	// live gefundenen Überlaufs bei "autovariance-biased" (bricht eine
	// spaltenpositions-basierte Regex, hier bewusst mitgetestet) und
	// einer Option ganz ohne "(default …)".
	out := `Encoder libx264 [libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10]:
    General capabilities: dr1 delay threads
    Threading capabilities: other
    Supported pixel formats: yuv420p yuvj420p yuv422p
libx264 AVOptions:
  -preset            <string>     E..V....... Set the encoding preset (cf. x264 --fullhelp) (default "medium")
  -profile           <string>     E..V....... Set profile restrictions (cf. x264 --fullhelp)
  -crf               <float>      E..V....... Select the quality for constant quality mode (from -1 to FLT_MAX) (default -1)
  -aq-mode           <int>        E..V....... AQ method (from -1 to INT_MAX) (default -1)
     none            0            E..V.......
     variance        1            E..V....... Variance AQ (complexity mask)
     autovariance-biased 3            E..V....... Auto-variance AQ with bias to dark scenes
  -x264-params       <dictionary> E..V....... Override the x264 configuration using a :-separated list of key=value parameters
`
	d := ParseDetail("libx264", out)
	if d.Description != "libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10" {
		t.Errorf("unexpected description: %q", d.Description)
	}
	if len(d.Options) != 5 {
		t.Fatalf("expected 5 options, got %d: %+v", len(d.Options), d.Options)
	}

	preset := d.Options[0]
	if preset.Name != "-preset" || preset.Type != "string" || preset.Default != `"medium"` {
		t.Errorf("unexpected -preset: %+v", preset)
	}
	if preset.Description != "Set the encoding preset (cf. x264 --fullhelp)" {
		t.Errorf("unexpected -preset description: %q", preset.Description)
	}

	profile := d.Options[1]
	if profile.Default != "" {
		t.Errorf("-profile has no default in the source, got %q", profile.Default)
	}

	crf := d.Options[2]
	if crf.Min != "-1" || crf.Max != "FLT_MAX" || crf.Default != "-1" {
		t.Errorf("unexpected -crf range/default: %+v", crf)
	}

	aq := d.Options[3]
	if len(aq.Choices) != 3 {
		t.Fatalf("expected 3 -aq-mode choices, got %d: %+v", len(aq.Choices), aq.Choices)
	}
	if aq.Choices[0].Name != "none" || aq.Choices[0].Value != "0" || aq.Choices[0].Description != "" {
		t.Errorf("unexpected 'none' choice: %+v", aq.Choices[0])
	}
	if aq.Choices[2].Name != "autovariance-biased" || aq.Choices[2].Value != "3" {
		t.Errorf("column-overflowing enum name not parsed correctly: %+v", aq.Choices[2])
	}

	dict := d.Options[4]
	if dict.Type != "dictionary" || dict.Default != "" {
		t.Errorf("unexpected -x264-params: %+v", dict)
	}
}

func TestParseDetailFilter(t *testing.T) {
	out := `Filter scale
  Scale the input video size and/or convert the image format.
    Inputs:
       #0: default (video)
    Outputs:
       #0: default (video)
scale AVOptions:
   w                 <string>     ..FV.....T. Output video width
   flags             <string>     ..FV....... Flags to pass to libswscale (default "")
   in_range          <int>        ..FV....... set input color range (from 0 to 2) (default auto)
     auto            0            ..FV.......
     full            2            ..FV.......
`
	d := ParseDetail("scale", out)
	if d.Description != "Scale the input video size and/or convert the image format." {
		t.Errorf("unexpected description: %q", d.Description)
	}
	if len(d.Options) != 3 {
		t.Fatalf("expected 3 options, got %d: %+v", len(d.Options), d.Options)
	}
	if d.Options[0].Name != "w" {
		t.Errorf("filter option name should have no leading dash: %+v", d.Options[0])
	}
	if d.Options[1].Default != `""` {
		t.Errorf("unexpected empty-string default: %+v", d.Options[1])
	}
	inRange := d.Options[2]
	if inRange.Min != "0" || inRange.Max != "2" || inRange.Default != "auto" {
		t.Errorf("unexpected in_range: %+v", inRange)
	}
	if len(inRange.Choices) != 2 || inRange.Choices[1].Name != "full" || inRange.Choices[1].Value != "2" {
		t.Errorf("unexpected in_range choices: %+v", inRange.Choices)
	}
}

func TestParseDetailMuxerWithoutOwnOptions(t *testing.T) {
	// Ein Muxer ohne eigenen AVOptions-Block (z.B. wenn ffmpeg für
	// dieses Format keine spezifischen Optionen registriert hat) darf
	// nicht crashen, nur eine leere Options-Liste liefern.
	out := `Muxer example [Example format]:
    Common extensions: ex.
`
	d := ParseDetail("example", out)
	if d.Description != "Example format" {
		t.Errorf("unexpected description: %q", d.Description)
	}
	if len(d.Options) != 0 {
		t.Errorf("expected no options, got %+v", d.Options)
	}
}

func TestValidKind(t *testing.T) {
	for _, k := range []string{"encoder", "decoder", "muxer", "demuxer", "filter"} {
		if !ValidKind(k) {
			t.Errorf("expected %q to be a valid kind", k)
		}
	}
	for _, k := range []string{"", "codec", "Encoder", "muxer;rm -rf"} {
		if ValidKind(k) {
			t.Errorf("expected %q to be rejected", k)
		}
	}
}
